#!/bin/sh

. "$(dirname "$0")/ensure-husky-runs.sh"

echo "#   git--dotfiles/hooks/post-commit"

branch_name=$(git symbolic-ref --short HEAD)
retcode=$?

if [ $retcode -ne 0 ]; then
    echo -e "\033[31mFailed to get the current branch name.\033[0m"
    exit 1
fi

WHITELIST=("my-fork" "libq" "li6in9muyou" "li6q")

remote_name=$(git config --get branch."$branch_name".remote)

if [ -z "$remote_name" ]; then
    echo -e "\033[31mNo remote tracking branch found for $branch_name\033[0m"
    exit 1
fi

remote_url=$(git config --get remote."$remote_name".url)

WHITELIST_MATCHED=false
for keyword in "${WHITELIST[@]}"; do
    if [ "$remote_name" = "$keyword" ] || echo "$remote_url" | grep -q "$keyword"; then
        WHITELIST_MATCHED=true
        break
    fi
done

if [ "$WHITELIST_MATCHED" = true ]; then
    git push
else
    echo -e "\033[31mREFUSE TO PUSH TO A PUBLIC REPO, REMOTE WAS $remote_name $remote_url\033[0m"
fi
