#!/bin/sh

echo "#   git--dotfiles/hooks/pre-commit, local hooks are disabled"
echo -n "CHECK IF 'DO NOT COMMIT' IS PRESENT"

DO_NOT_COMMIT=$(git diff --staged --patch | grep 'DO NOT COMMIT' -i -C 6)

if [ -n "$DO_NOT_COMMIT" ]; then
  echo
  echo -e "\033[31mAborted: diff contains 'DO NOT COMMIT'"
  echo "Aborted: diff contains 'DO NOT COMMIT'"
  echo -e "Aborted: diff contains 'DO NOT COMMIT'\033[0m"
  echo
  git diff --staged --patch --color | grep 'DO NOT COMMIT' -C 8
  exit 1
else
  echo -e "\033[32m OK\033[0m"
fi

exit 0
